# Generated by Django 5.0.4 on 2024-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('lugares', models.CharField(max_length=2)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
