# Generated by Django 5.0.4 on 2024-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrição', models.CharField(max_length=100)),
                ('fotografia', models.ImageField(upload_to='fotos_pratos')),
                ('categoria', models.CharField(choices=[('LANCHE', 'Lanche'), ('PIZZA', 'Pizza'), ('HOTDOG', 'Hotdog')], default='', max_length=100)),
            ],
        ),
    ]
