# Generated by Django 5.0.4 on 2024-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('fotografia', models.ImageField(upload_to='fotos_bebidas')),
                ('categoria', models.CharField(choices=[('REFRIGERANTES', 'Refrigerantes'), ('ALCOOLICAS', 'Alcoolicas')], max_length=13)),
            ],
        ),
    ]
