# Generated by Django 5.0.4 on 2024-05-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_bebida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebida',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
