# Generated by Django 5.0.4 on 2024-05-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_rename_descricao_bebida_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebida',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='prato',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.CharField(choices=[('REFRIGERANTES', 'Refrigerantes'), ('ALCOOLICAS', 'Alcoolicas')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('LANCHE', 'Lanche'), ('PIZZA', 'Pizza'), ('HOTDOG', 'Hotdog')], default='', max_length=20),
        ),
    ]
