# Generated by Django 5.0.4 on 2024-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_rename_descrição_bebida_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='fotografia',
            field=models.ImageField(upload_to='media/fotos_bebidas'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='fotografia',
            field=models.ImageField(upload_to='media/fotos_pratos'),
        ),
    ]
