# Generated by Django 5.0.4 on 2024-05-16 00:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_prato_valor_alter_bebida_foto_alter_prato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
