# Generated by Django 5.0.4 on 2024-05-16 00:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0008_bebida_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='valor',
        ),
        migrations.AddField(
            model_name='prato',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
