# Generated by Django 5.0.4 on 2024-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_alter_prato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
    ]
