# Generated by Django 5.0.4 on 2024-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0011_alter_prato_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
