# Generated by Django 5.0.4 on 2024-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_prato_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='quantidade',
            field=models.IntegerField(choices=0, default=0),
        ),
    ]
