# Generated by Django 5.0.4 on 2024-05-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0013_alter_prato_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='quantidade',
        ),
    ]
