# Generated by Django 5.0.4 on 2024-06-07 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0014_remove_prato_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
