# Generated by Django 5.0.4 on 2024-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0015_bebida_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
