# Generated by Django 5.0.4 on 2024-07-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0016_alter_prato_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
