# Generated by Django 5.0.4 on 2024-05-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garcom',
            new_name='Funcionario',
        ),
    ]
