# Generated by Django 5.0.4 on 2024-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('GARCOM', 'garcom'), ('COZINHEIRO', 'cozinheiro'), ('CAIXA', 'caixa')], default='', max_length=20)),
            ],
        ),
    ]
